config/routes.rb
Bip::Application.routes.draw do

  resources :plays

  resources :artists do
    resources :tracks
  end
  
  resources :albums do
    resources :tracks
  end

  resources :votes

  resources :tracks do
    resource :album
    resource :artist
  end

  resources :playlists do
    resources :tracks, :controller => :playlist_items do
      resources :plays
    end
  end
  
  match "/playlists/:playlist_id/tracks/:id/play(.:format)" => "playlist_items#play"
  match "/playlists/:id/play(.:format)" => "playlists#play"
  match "/playlists/:id/next(.:format)" => "playlists#next"
  match "/playlists/:id/pause" => "playlists#pause"
  
  match "/search(.:format)" => "Search#index"
  
  resources :playlist_items

  root :to => "playlists#index"

end

app/models/play.rb
class Play < ActiveRecord::Base
	belongs_to :playlist_item
	
	after_save :touch_playlist
	
	def touch_playlist
	  playlist_item.playlist.touch if playlist_item && playlist_item.playlist
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  # GET /plays
  # GET /plays.xml
  def index
    @plays = Play.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @plays }
    end
  end

  # GET /plays/1
  # GET /plays/1.xml
  def show
    @play = Play.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @play }
    end
  end

  # GET /plays/new
  # GET /plays/new.xml
  def new
    @play = Play.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @play }
    end
  end

  # GET /plays/1/edit
  def edit
    @play = Play.find(params[:id])
  end

  # POST /plays
  # POST /plays.xml
  def create
    @play = Play.new(params[:play])

    respond_to do |format|
      if @play.save
        format.html { redirect_to(@play, :notice => 'Play was successfully created.') }
        format.xml  { render :xml => @play, :status => :created, :location => @play }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @play.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /plays/1
  # PUT /plays/1.xml
  def update
    @play = Play.find(params[:id])

    respond_to do |format|
      if @play.update_attributes(params[:play])
        format.html { redirect_to(@play, :notice => 'Play was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @play.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.xml
  def destroy
    @play = Play.find(params[:id])
    @play.destroy

    respond_to do |format|
      format.html { redirect_to(plays_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/plays/_form.html.erb
<%= form_for(@play) do |f| %>
  <% if @play.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@play.errors.count, "error") %> prohibited this play from being saved:</h2>

      <ul>
      <% @play.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playlist_item_id %><br />
    <%= f.text_field :playlist_item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plays/edit.html.erb
<h1>Editing play</h1>

<%= render 'form' %>

<%= link_to 'Show', @play %> |
<%= link_to 'Back', plays_path %>

app/views/plays/index.html.erb
<h1>Listing plays</h1>

<table>
  <tr>
    <th>Playlist item</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @plays.each do |play| %>
  <tr>
    <td><%= play.playlist_item_id %></td>
    <td><%= link_to 'Show', play %></td>
    <td><%= link_to 'Edit', edit_play_path(play) %></td>
    <td><%= link_to 'Destroy', play, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Play', new_play_path %>

app/views/plays/new.html.erb
<h1>New play</h1>

<%= render 'form' %>

<%= link_to 'Back', plays_path %>

app/views/plays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Playlist item:</b>
  <%= @play.playlist_item_id %>
</p>


<%= link_to 'Edit', edit_play_path(@play) %> |
<%= link_to 'Back', plays_path %>