config/routes.rb
Bip::Application.routes.draw do

  resources :plays

  resources :artists do
    resources :tracks
  end
  
  resources :albums do
    resources :tracks
  end

  resources :votes

  resources :tracks do
    resource :album
    resource :artist
  end

  resources :playlists do
    resources :tracks, :controller => :playlist_items do
      resources :plays
    end
  end
  
  match "/playlists/:playlist_id/tracks/:id/play(.:format)" => "playlist_items#play"
  match "/playlists/:id/play(.:format)" => "playlists#play"
  match "/playlists/:id/next(.:format)" => "playlists#next"
  match "/playlists/:id/pause" => "playlists#pause"
  
  match "/search(.:format)" => "Search#index"
  
  resources :playlist_items

  root :to => "playlists#index"

end

app/models/playlist_item.rb
class PlaylistItem < ActiveRecord::Base
  belongs_to :track
  belongs_to :playlist, :counter_cache => true
  has_many :votes, :dependent => :destroy
  has_many :plays
  
  validates_presence_of :playlist_id
  validates_presence_of :spotify_id
  # The same track can only be added once per playlist:
  #http://stackoverflow.com/questions/2533502/rails-3-validate-combined-values
  validates :track_id, :presence => true, :uniqueness => {:scope => :playlist_id}

  def total_votes_count
    votes_count.to_i + previous_votes_count.to_i
  end

  def name
    track.full_name
  end
end

# == Schema Information
#
# Table name: playlist_items
#
#  id          :integer         not null, primary key
#  playlist_id :integer
#  track_id    :integer
#  votes_count :integer
#  created_at  :datetime
#  updated_at  :datetime
#  spotify_id  :string(255)
#

app/controllers/playlist_items_controller.rb
class PlaylistItemsController < ApplicationController

  add_crumb 'Spellistor', :playlists_path

  # GET /playlist_items
  # GET /playlist_items.xml
  def index
    @playlist_items = PlaylistItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @playlist_items }
    end
  end

  # GET /playlist_items/1
  # GET /playlist_items/1.xml
  def show
    @playlist_item = PlaylistItem.find(params[:id])

    unless params[:playlist_id].blank?
      @playlist = Playlist.find(params[:playlist_id])
      add_crumb @playlist.name, playlist_path(@playlist)
    end
    add_crumb @playlist_item.track.full_name

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @playlist_item }
    end
  end

  # GET /playlist_items/new
  # GET /playlist_items/new.xml
  def new
    @playlist_item = PlaylistItem.new
    unless params[:playlist_id].blank?
      @playlist = Playlist.find(params[:playlist_id])
      unless @playlist.nil?
        @playlist_item.playlist_id = @playlist.id
      end
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @playlist_item }
    end
  end

  # GET /playlist_items/1/edit
  def edit
    @playlist_item = PlaylistItem.find(params[:id])
  end

  # POST /playlist_items
  # POST /playlist_items.xml
  def create
    @playlist_item = PlaylistItem.new(params[:playlist_item])
    
    # Make sure we don't create a new track if we already have it:
    @track = Track.find_or_create_by_spotify_id(params[:playlist_item][:spotify_id])
    
    unless @track.blank? || params[:playlist_item][:spotify_id].blank? 
      # Find the song with Spotifys metadata API 
      # (using a wrapper from http://github.com/philnash/meta-spotify)
      found_track = MetaSpotify::Track.lookup(params[:playlist_item][:spotify_id])
    
      # Only save data if MetaSpotify could find the song
      unless found_track.blank?
        @track.name = found_track.name
        @track.artist = found_track.artists.first.name
        @track.album = found_track.album.name
        @track.href = found_track.uri
        @track.length = found_track.length
        @track.popularity = found_track.popularity
        @track.votes_count = 0
        @track.cover_url = @track.fetch_cover_url
        @track.save!
    
        # Save the playlist_id from the form:
        unless params[:playlist_item][:playlist_id].blank?
          @playlist_item.playlist_id = params[:playlist_item][:playlist_id]
        end
        
        # Only save track_id if all previous worked
        @playlist_item.track_id = @track.id
      end # unless found_track.blank?
    end # unless @track.blank? || params[:spotify_id].blank? 
    
    respond_to do |format|
      if @playlist_item.save
        format.html { redirect_to(@playlist_item.playlist)}#, :notice => 'Playlist item was successfully created.') }
        format.xml  { render :xml => @playlist_item, :status => :created, :location => @playlist_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @playlist_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /playlist_items/1
  # PUT /playlist_items/1.xml
  def update
    @playlist_item = PlaylistItem.find(params[:id])

    respond_to do |format|
      if @playlist_item.update_attributes(params[:playlist_item])
        format.html { redirect_to(@playlist_item, :notice => 'Playlist item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @playlist_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /playlist_items/1
  # DELETE /playlist_items/1.xml
  def destroy
    @playlist_item = PlaylistItem.find(params[:id])
    @playlist_item.destroy

    respond_to do |format|
      format.html { redirect_to(playlist_items_url) }
      format.xml  { head :ok }
    end
  end
  
  def play
    @playlist_item = PlaylistItem.find(params[:id])
    if @playlist_item
      # Increment amount of plays
      #@playlist_item.??? = @track.??? + 1
      
      # Reset number of votes
      @playlist_item.previous_votes_count = @playlist_item.previous_votes_count.to_i + @playlist_item.votes_count.to_i
      @playlist_item.votes_count = 0
      
      # Respond with XML format:
      respond_to do |format|
        format.html { redirect_to(playlist_path(@playlist_item.playlist)) }
        format.xml  { redirect_to(playlist_item_path(@playlist_item, :format => :xml)) }
      end
    end
  end
end

app/helpers/playlist_items_helper.rb
module PlaylistItemsHelper
end

app/views/playlist_items/_form.html.erb
<%= form_for(@playlist_item) do |f| %>
  <% if @playlist_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist_item.errors.count, "error") %> prohibited this playlist_item from being saved:</h2>

      <ul>
      <% @playlist_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= f.label :playlist_id %><%#, Playlist.human_name.humanize %><br />
    <%= f.hidden_field :playlist_id %>
  </div>
<!--
  <div class="field">
    <%#= f.label :track_id %><%#, Track.human_name.humanize %><br />
    <%#= f.text_field :track_id %>
  </div>
-->

  <h3>Lägg till låt via:</h3>

  <div class="field">
    <%= label_tag 'searched_false', 'Spotify-URI:' %>
    <%= radio_button_tag 'searched', false, true %>
    <%#= f.label :spotify_id, 'Spotify-ID' %><br />
    spotify:track:
	<%= text_field_tag 'spotify_id', '' %>
  </div>

  <div class="field">
  	<%= label_tag 'searched_true', 'Sökning:' %>
  	<%= radio_button_tag 'searched', true %>

  	<%= search_field_tag 'query' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlist_items/edit.html.erb
<h1>Editing playlist_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist_item %> |
<%= link_to 'Back', playlist_items_path %>

app/views/playlist_items/index.html.erb
<h1>Listing playlist_items</h1>

<table>
  <tr>
    <th>Playlist</th>
    <th>Track</th>
    <th>Votes count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @playlist_items.each do |playlist_item| %>
  <tr>
    <td><%= link_to playlist_item.playlist.name, playlist_item.playlist unless playlist_item.playlist.nil? %></td>
    <td><%= link_to playlist_item.track.name, playlist_item.track unless playlist_item.track.nil? %></td>
    <td><%= playlist_item.votes_count %></td>
    <td><%= link_to 'Show', playlist_item %></td>
    <td><%= link_to 'Edit', edit_playlist_item_path(playlist_item) %></td>
    <td><%= link_to 'Destroy', playlist_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Playlist item', new_playlist_item_path %>

app/views/playlist_items/new.html.erb
<h1>Ny låt</h1>

<%= render 'form' %>

app/views/playlist_items/show.html.erb
<div class="page-header">

<div class="listen" style="float: right">
  <%= link_to image_tag("icon_spotify.png", :valign => 'sub') + " Visa i Spotify", @playlist_item.track.href, { :class => 'button listen' } %>
</div>

<%= image_tag @playlist_item.track.cover_url || 'cover_unknown.png', {:class => 'artist_cover', :width => 64} %>

<h2><%= @playlist_item.track.artist %></h2>
<h1><%= @playlist_item.track.name %></h1>

<div class="album">
  <%= @playlist_item.track.album %>
</div>

</div>

<p>
  Längd:
  <%= @playlist_item.track.length_as_string %>
</p>

<!--
<div id="disqus_thread"></div>
<script type="text/javascript">
  /**
    * var disqus_identifier; [Optional but recommended: Define a unique identifier (e.g. post id or slug) for this thread] 
    */
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://bignetworkinternetplayer.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=bignetworkinternetplayer">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
-->

<h3>Finns i <%= @playlist_item.track.playlists.count %> spellistor:</h3>

<ul>
	<% unless @playlist_item.track.blank? %>
  <% @playlist_item.track.playlists.each do |playlist| %>
		<li><%= link_to playlist.name, playlist %></li>
	<% end %>
  <% end %>
</ul>

<h3>Röster: <%= @playlist_item.votes.size %> (totalt <%= @playlist_item.track.votes.count %> i alla spellistor)</h3>