config/routes.rb
Bip::Application.routes.draw do

  resources :plays

  resources :artists do
    resources :tracks
  end
  
  resources :albums do
    resources :tracks
  end

  resources :votes

  resources :tracks do
    resource :album
    resource :artist
  end

  resources :playlists do
    resources :tracks, :controller => :playlist_items do
      resources :plays
    end
  end
  
  match "/playlists/:playlist_id/tracks/:id/play(.:format)" => "playlist_items#play"
  match "/playlists/:id/play(.:format)" => "playlists#play"
  match "/playlists/:id/next(.:format)" => "playlists#next"
  match "/playlists/:id/pause" => "playlists#pause"
  
  match "/search(.:format)" => "Search#index"
  
  resources :playlist_items

  root :to => "playlists#index"

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  #has_many :tracks, :order => 'votes_count DESC'
  has_many :playlist_items, :order => 'votes_count DESC, created_at ASC'
  has_many :tracks, :through => :playlist_items
  has_many :plays, :through => :playlist_items, :order => :created_at
  has_many :votes, :through => :playlist_items
  
  def latest_status_at
    if is_playing? && plays.first
      plays.first.created_at
    else
      updated_at
    end
  end
  
end

# == Schema Information
#
# Table name: playlists
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  is_playing :integer
#

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  # GET /playlists
  # GET /playlists.xml
  def index
    @playlists = Playlist.all :include => [:plays, :votes, :tracks, :playlist_items]

    add_crumb "Spellistor"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @playlists }
      format.json  { render :json => @playlists }
    end
  end

  # GET /playlists/1
  # GET /playlists/1.xml
  def show
    @playlist = Playlist.find(params[:id])
    add_crumb "Spellistor", '/playlists'
    add_crumb @playlist.name

    @display_type = params[:display]

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @playlist }
      format.json { render :json => @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.xml
  def new
    @playlist = Playlist.new
    add_crumb "Spellistor", '/playlists'
    add_crumb "Ny spellista"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])
    add_crumb @playlist.name
  end

  # POST /playlists
  # POST /playlists.xml
  def create
    @playlist = Playlist.new(params[:playlist])

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to(@playlist, :notice => 'Playlist was successfully created.') }
        format.xml  { render :xml => @playlist, :status => :created, :location => @playlist }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @playlist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.xml
  def update
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to(@playlist, :notice => 'Playlist was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @playlist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.xml
  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to(playlists_url) }
      format.xml  { head :ok }
    end
  end
  
  def play
    @playlist = Playlist.find(params[:id])
    
    # TODO: Replace TRACK with PLAYLIST_ITEM
    # TODO: TEST MOAR!
    
    if @playlist && @playlist.playlist_items
      
      # Mark the playlist as playing:
      @playlist.is_playing = true
      @playlist.save!
      
      # Find the first track
      @playlist_item = @playlist.playlist_items.first
      
      respond_to do |format|
        format.html { redirect_to("/playlists/#{@playlist.id}/tracks/#{@playlist_item.id}/play") }
        format.xml  { redirect_to("/playlists/#{@playlist.id}/tracks/#{@playlist_item.id}/play.xml") }
      end
      # Redirect to track
      
    end
  end
  
  def pause
    # 
    @playlist = Playlist.find(params[:id])
    if @playlist
      @playlist.is_playing = false
      @playlist.save!
    end
    
    redirect_to :back
    
    # TODO: Connect to the playback server and pause it as well!
  end

  def next
    play
  end
  
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_playing %>
    <%= f.check_box :is_playing %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn primary' %>
    <%= link_to 'Avbryt', @playlist, :class => 'btn' %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Ändrar spellista</h1>

<%= render 'form' %>

app/views/playlists/index.html.erb
<div class="page-header">
	<h1>Vilken spellista? <small>Välj en så kan du lägga till eller rösta på låtar du gillar</small></h1>
	<!--
	<h1>Lägg till eller rösta på låtar du gillar<small>i någon av spellistorna:</small></h1>
	-->
	<!--
	<h1>➊ Välj spellista &nbsp; <br/>➋ Lägg till en låt <br/>➌ Rösta upp låtar du gillar</h1>
	-->
</div>

<table class="playlists zebra-striped" id="all_playlists">
	<thead>
		<tr>
			<th>Namn</th>
			<th>Låtar</th>
			<th>Röster</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>
<% @playlists.each do |playlist| %>
	<tr class="playlist">
		<td><%= link_to playlist.name, playlist %></td>
		<td>
			<%= playlist.playlist_items.size %>
		</td>
		<td>
			<%= playlist.votes.size %>
		</td>
		<td>
			<% if playlist.playlist_items.count > 0 %>
			
				<% if playlist.is_playing? %>
					<span class="label success"><%= image_tag 'icons-gentleface/white/playback_play_icon&16.png', :style => 'vertical-align: -5px;' %> Spelar nu </span>
				<% else %>
					<span class="label"><%= image_tag 'icons-gentleface/white/playback_pause_icon&16.png', :style => 'vertical-align: -5px;' %> Pausad </span>
				<% end %>

				&nbsp;
			
				<%= link_to "#{playlist.playlist_items.first.track.artist} - #{playlist.playlist_items.first.track.name}", playlist_track_path(playlist, playlist.playlist_items.first) %>
			
				<%= timeago playlist.latest_status_at, :inner_html => "för #{time_ago_in_words playlist.latest_status_at, true} sedan" %>
			
			<% end %>
		</td>
	</tr>
<% end %>	

</tbody>
</table>

<div class="well">
eller &nbsp; <%= link_to '+ Lägg till en spellista', new_playlist_path, :class => 'btn' %>
</div>
<!--
<div class="table_adder">
	<%= link_to '+', new_playlist_path, { :class => 'icon small add' } %>
	<%= link_to '+ Lägg till en spellista', new_playlist_path, :class => '' %>
</div>
-->

app/views/playlists/new.html.erb
<div class="page-header">
  <h1>Ny spellista <small>&mdash; En alldeles egen</small></h1>
</div>

<%= form_for(@playlist, :html => {:class => 'form-stacked'}) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Vad vill du kalla spellistan?' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn primary' %>
    <%= link_to 'Avbryt', playlists_path, :class => 'btn' %> 
  </div>
<% end %>

app/views/playlists/show.html.erb
<% if @playlist.is_playing? %>
<div class="now_playing">
	<% unless @playlist.playlist_items.blank? %>
		<a href="<%= playlist_item_path(@playlist.playlist_items.first) %>">
		<span class="cover">
			<span class="overlay"></span>
			<%= image_tag @playlist.playlist_items.first.track.cover_url || 'cover_unknown.png' %>
		</span>
		</a>
		<span class="name">
			<%= link_to image_tag("icon_spotify.png"), @playlist.playlist_items.first.track.href, :class => 'spotify' %>
			<%= link_to @playlist.playlist_items.first.track.name, @playlist.playlist_items.first %>
		</span>
		<span class="artist"><%= @playlist.playlist_items.first.track.artist %></span>
		<span class="votes"><span class="count"><%= @playlist.playlist_items.first.votes.size %></span> röster</span>
		<span class="duration">
			<span class="current">~ 1:05</span>
			<span class="progressbar">
				<span class="current" style="width: 35%;"></span>
			</span>
			<span class="total">
				<%= @playlist.playlist_items.first.track.length_as_string %>
			</span>
		</span>
	<% end %>
</div>
<% end %>

<div class="page-header">
	<h1>
		<%= @playlist.name %>

		<div id="share_playlist">
		<a href="<%= request.fullpath %>" title="Dela spellistan" class="share_link popup_enabler tooltip"><%= image_tag 'icons-sencha/action.png' %></a>
		<div id="share_playlist_options" style="display: none;" class="popup">
			<%= link_to 'x', '', :class => 'close' %>
			<p>Kommer snart...</p>
			<p>
				Dela via:<br/>
				[F] Facebook<br/>
				[E] Epost<br/>
				[T] Twitter<br/>
				[U] URL<br/>
			</p>
			<p>
				Skicka denna adressen till vänner:<br/>
				<input type="text" value="<%= playlist_url @playlist %>" />
			</p>
			<p>
				<!-- Inspired by: http://spotibot.com/playlist/ -->
				Dra och släpp denna ikon till en ny Spotify-spellista:
				<div style="background: url('/images/icon_spotify.png') center center no-repeat; cursor: pointer; display: inline-block; height: 24px; overflow: hidden; width: 24px;">
					<div style="display: inline-block; height: 100%; opacity: 0; width: 100%">
						<% @playlist.playlist_items.each do |playlist_item| %><%= playlist_item.spotify_id %><% end %>
					</div>
				</div><br/>
				Eller kopiera denna text och klistra in i en ny Spotify-spellista:<br/>
				<textarea rows="<%= @playlist.playlist_items.count %>" cols="35">
				<% @playlist.playlist_items.each do |playlist_item| %>
<%= playlist_item.spotify_id %>
<% end %></textarea>
			</p>
		</div>
	</div>

	<%= link_to 'Admin-inställningar', "#", {:class => 'tooltip popup_enabler', :id => 'admin_settings_link', :title => 'Admin-inställningar', :style => ''} %>

	<div id="admin_settings" class="popup" style="display: none;">
		<p>Playback-kod: ASDaeqweq23</p>
		
		<span class="playback_controls">
			<%= link_to "Föregående", "#", { :title => 'Endast för ADMIN', :class => 'tooltip previous' }  %>
			<% if @playlist.is_playing? %>
				<%= link_to "Pausa", "/playlists/#{@playlist.id}/pause", { :title => 'Endast för ADMIN', :class => 'tooltip pause' }  %>
			<% else %>
				<%= link_to "Spela upp", "/playlists/#{@playlist.id}/play", { :title => 'Endast för ADMIN', :class => 'tooltip play' }  %>
			<% end %>
			<%= link_to "Nästa", "/playlists/#{@playlist.id}/next", { :title => 'Endast för ADMIN', :class => 'tooltip next' } %>
		</span>
	</div>
	</h1>
	<br/>
</div>

<div class="well">
<form method="get" action="/search" class="form-stacked">
	<fieldset><!--<legend>Lägg till en låt</legend>-->
		<input type="hidden" name="playlist_id" value="<%= @playlist.id %>" />
		<label for="add_playlist_search_q">Lägg till en låt:</label>
		<input name="q" id="add_playlist_search_q" type="search" placeholder="Sök artist/album/låt" value="<%= h params[:q] %>" />
		<button class="btn primary" type="submit">Sök</button>
	</fieldset>
</form>
</div>

<!--
<div id="playlist_tip">
	<form method="get" action="/search">
		<input type="hidden" name="playlist_id" value="<%= @playlist.id %>" />
		<label for="add_playlist_search_q">Lägg till låt:</label>
		<input name="q" id="add_playlist_search_q" type="search" placeholder="Artist/album/låt" value="<%= h params[:q] %>" />
	</form>
  <%= link_to '+ Lägg till en låt', "/search?playlist_id=#{@playlist.id}", { :class => 'button add popup_enabler', :id => 'add_playlist_item' } %>
	<div id="playlist_add" style="<%= 'display: none;' if params[:q].blank? %>" class="popup">
		<%= link_to 'x', '', :class => 'close' %>
		<form>
			<label for="add_playlist_search_q">Sök efter:</label>
			<input name="q" id="add_playlist_search_q" type="search" placeholder="Artist/album/låt" value="<%= h params[:q] %>" />
		</form>
	</div>
</div>
-->

<!--
<p class="display_mode">
  <%= image_tag 'icons-glyphish/12-eye.png', :class => 'show_as' %> Visa som
  <%= link_to image_tag('icons-gentleface/black/list_bullets_icon&16.png'), { :display => 'table'}, { :class => ('current' if @display_type != 'list') } %>
  <%= link_to image_tag('icons-gentleface/black/2x2_grid_icon&16.png'),  { :display => 'list'},  { :class => ('current' if @display_type == 'list') } %>
</p>
-->

<ul class="tabs display_style" style="float: right">
  <li class="<%= 'active' if @display_type == 'table' %>">
  	<%= link_to image_tag('icons-gentleface/black/list_bullets_icon&16.png') + ' Tabell', { :display => 'table'} %>
  </li>
  <li class="<%= 'active' if @display_type != 'table' %>">
  	<%= link_to image_tag('icons-gentleface/black/2x2_grid_icon&16.png') + ' Lista',  { :display => 'list'} %>
  </li>
</ul>

<% if @display_type == 'table' %>

  
<% if @playlist.playlist_items.empty? %>
	Inga låtar.
<% else %>
	
	<table class="tracks zebra-striped" id="playlist_tracks">
		<thead>
		<tr>
			<th></th>
			<th class="name">Namn</th>
			<th class="artist">Artist</th>
<!--			<th class="album">Album</th>-->
	<!--		<th>Href</th>-->
<!--			<th>Popularitet</th>-->
			<th>Längd</th>
			<th class="action votes" colspan="2">Röster</th>
			<th></th>
		</tr>
		</thead>
		<tbody>
		<% @playlist.playlist_items.each_with_index do |playlist_item, index| %>
			<tr class="track <%= 'highlight' if playlist_item.track.id == params[:highlight_item_id].to_i %> <%= 'current' if @playlist.is_playing? && index == 0 %>">
				<td class="cover">
					<a href="<%= playlist_item_path(playlist_item) %>">
						<span class="overlay"></span>
						<%= image_tag playlist_item.track.cover_url || 'cover_unknown.png' %>
					</a>
				</td>
				<td class="name">
					<% if playlist_item.track %>
						<%= link_to playlist_item.track.name, playlist_track_path(@playlist, playlist_item) %>
					<% else %>
						?
					<% end %>
					<% if @playlist.is_playing? && index == 0 %>
						<span class="label success">Spelas nu</span>
					<% end %>
				</td>
				<td class="artist"><%= playlist_item.track.artist %></td>
<!--				<td class="album"><%= playlist_item.track.album %></td>-->
	<!--			<td><%= link_to playlist_item.track.href, playlist_item.track.href %></td>-->
<!--				<td>
					<% unless playlist_item.track.popularity.blank? %>
					<% 
						(0..(playlist_item.track.popularity*10).to_i).each do |p|
							%>|<%
						end 
					end
					%>
				</td>
-->
				<td><%= playlist_item.track.length_as_string %></td>
				<td class="action votes">
					<%= playlist_item.votes.size %>
				</td>
				<td class="action vote">
					<% if @playlist.is_playing? && index != 0 %>
						<%= link_to "+", votes_path("playlist_item_id" => playlist_item.id), { :remote => true, :method => :post, :class => 'icon vote tooltip', :title => 'Rösta'} %>
						<%#= link_to "+ ❤", votes_path("[vote][playlist_item_id]" => playlist_item.id), { :remote => true, :method => :post, :class => 'icon vote', :title => 'Rösta'} %>
					<% end %>
				</td>
				<td class="share"><%= link_to image_tag('icons-sencha/action.png'), playlist_item.track.href, {:title => 'Öppna i Spotify', :class => 'tooltip' } %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
<% end %>	

<!--
<div class="table_adder">
	<%= link_to '+', new_playlist_track_path(@playlist), { :class => 'icon small add' } %>
	<%= link_to 'Lägg till en låt', new_playlist_track_path(@playlist) %>
</div>
-->

<% else # (if @display_type == 'list' or @display_type.nil %>

  <ol class="tracks media-grid">
  <% if @playlist.playlist_items.empty? %>
		Inga låtar.
	<% else %>
    <% @playlist.playlist_items.each_with_index do |playlist_item, index| %>
      <li class="track <%= 'current' if @playlist.is_playing? && index == 0 %>">
      	<a href="<%= playlist_track_path(@playlist, playlist_item) %>">
					<!--<span class="cover" style="background-image: url('<%#= playlist_item.track.cover_url %>');">-->
						<span class="overlay"></span>
						<!--<a href="<%= playlist_track_path(@playlist, playlist_item) %>">-->
						<%= image_tag(playlist_item.track.cover_url || 'cover_unknown.png', {:height => 126, :width => 126}) %>
						<!--</a>-->
					<!--</span>-->
        	<%#= image_tag(playlist_item.track.cover_url || '', { :alt => "", :height => 126, :width => 126, :class => 'cover' } ) %>
			<span class="description">
				<span class="artist"><%= playlist_item.track.artist %></span>
				<span class="name"><%= playlist_item.track.name %></span>
			</span>
        </a>
        <% if @playlist.is_playing? && index != 0 %>
        <span class="votes"><%= link_to "#{playlist_item.votes.size} ❤", votes_path("[vote][playlist_item_id]" => playlist_item.id), { :remote => true, :method => :post, :class => 'icon vote tooltip', :title => 'Rösta'} %></span>
        <% end %>
      </li>
    <% end %>
  <% end %>
  </ol>

<% end %>